[package]
name = "bosco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-encoder = "0.207.0"
wasmprinter = "0.207.0"
