[package]
name = "bosco"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
thiserror = "1.0.61"
wasm-encoder = "0.210.0"

[dev-dependencies]
wasmi = "0.32.3"
wasmprinter = "0.210.0"
ariadne = "0.4.1"
